[
    WHITE_KNIGHT_PIECE_ID,
    WHITE_BISHOP_PIECE_ID,
    WHITE_ROOK_PIECE_ID,
    WHITE_QUEEN_PIECE_ID,
    WHITE_KING_PIECE_ID,
    WHITE_PAWN_PIECE_ID,
    EMPTY_SQUARE_ID,
] = [6, 5, 4, 3, 2, 7, 0] 

BLACK_PIECE_ID_OFFSET = 6
