
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineSystem.cmake:211 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Windows - 10.0.22000 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      1
      Microsoft (R) Build Engine version 16.2.37902+b5aaefc9f for .NET Framework
      Copyright (C) Microsoft Corporation. All rights reserved.
      
      Build started 7/21/2023 8:30:52 PM.
      Project "C:\\Users\\theor\\Desktop\\chess_game\\chess_game_cpp\\CMakeFiles\\3.27.0\\CompilerIdC\\CompilerIdC.vcxproj" on node 1 (default targets).
      PrepareForBuild:
        Creating directory "Debug\\".
      C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\MSBuild\\Microsoft\\VC\\v160\\Microsoft.CppBuild.targets(434,5): warning MSB8003: The WindowsSDKDir property is not defined. Some build tools may not be found. [C:\\Users\\theor\\Desktop\\chess_game\\chess_game_cpp\\CMakeFiles\\3.27.0\\CompilerIdC\\CompilerIdC.vcxproj]
        Creating directory "Debug\\CompilerIdC.tlog\\".
      InitializeBuildStatus:
        Creating "Debug\\CompilerIdC.tlog\\unsuccessfulbuild" because "AlwaysCreate" was specified.
      ClCompile:
        C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.22.27905\\bin\\HostX64\\x64\\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc142.pdb" /Gd /TC /FC /errorReport:queue CMakeCCompilerId.c
        CMakeCCompilerId.c
      Link:
        C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.22.27905\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdC.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdC.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdC.lib" /MACHINE:X64 Debug\\CMakeCCompilerId.obj
      LINK : fatal error LNK1181: cannot open input file 'kernel32.lib' [C:\\Users\\theor\\Desktop\\chess_game\\chess_game_cpp\\CMakeFiles\\3.27.0\\CompilerIdC\\CompilerIdC.vcxproj]
      Done Building Project "C:\\Users\\theor\\Desktop\\chess_game\\chess_game_cpp\\CMakeFiles\\3.27.0\\CompilerIdC\\CompilerIdC.vcxproj" (default targets) -- FAILED.
      
      Build FAILED.
      
      "C:\\Users\\theor\\Desktop\\chess_game\\chess_game_cpp\\CMakeFiles\\3.27.0\\CompilerIdC\\CompilerIdC.vcxproj" (default target) (1) ->
      (PrepareForBuild target) -> 
        C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\MSBuild\\Microsoft\\VC\\v160\\Microsoft.CppBuild.targets(434,5): warning MSB8003: The WindowsSDKDir property is not defined. Some build tools may not be found. [C:\\Users\\theor\\Desktop\\chess_game\\chess_game_cpp\\CMakeFiles\\3.27.0\\CompilerIdC\\CompilerIdC.vcxproj]
      
      
      "C:\\Users\\theor\\Desktop\\chess_game\\chess_game_cpp\\CMakeFiles\\3.27.0\\CompilerIdC\\CompilerIdC.vcxproj" (default target) (1) ->
      (Link target) -> 
        LINK : fatal error LNK1181: cannot open input file 'kernel32.lib' [C:\\Users\\theor\\Desktop\\chess_game\\chess_game_cpp\\CMakeFiles\\3.27.0\\CompilerIdC\\CompilerIdC.vcxproj]
      
          1 Warning(s)
          1 Error(s)
      
      Time Elapsed 00:00:02.50
      
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      1
      Microsoft (R) Build Engine version 16.2.37902+b5aaefc9f for .NET Framework
      Copyright (C) Microsoft Corporation. All rights reserved.
      
      Build started 7/21/2023 8:30:55 PM.
      Project "C:\\Users\\theor\\Desktop\\chess_game\\chess_game_cpp\\CMakeFiles\\3.27.0\\CompilerIdC\\CompilerIdC.vcxproj" on node 1 (default targets).
      PrepareForBuild:
        Creating directory "Debug\\".
      C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\MSBuild\\Microsoft\\VC\\v160\\Microsoft.CppBuild.targets(434,5): warning MSB8003: The WindowsSDKDir property is not defined. Some build tools may not be found. [C:\\Users\\theor\\Desktop\\chess_game\\chess_game_cpp\\CMakeFiles\\3.27.0\\CompilerIdC\\CompilerIdC.vcxproj]
        Creating directory "Debug\\CompilerIdC.tlog\\".
      InitializeBuildStatus:
        Creating "Debug\\CompilerIdC.tlog\\unsuccessfulbuild" because "AlwaysCreate" was specified.
      ClCompile:
        C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.22.27905\\bin\\HostX64\\x64\\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc142.pdb" /Gd /TC /FC /errorReport:queue CMakeCCompilerId.c
        CMakeCCompilerId.c
      Link:
        C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.22.27905\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdC.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdC.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdC.lib" /MACHINE:X64 Debug\\CMakeCCompilerId.obj
      LINK : fatal error LNK1181: cannot open input file 'kernel32.lib' [C:\\Users\\theor\\Desktop\\chess_game\\chess_game_cpp\\CMakeFiles\\3.27.0\\CompilerIdC\\CompilerIdC.vcxproj]
      Done Building Project "C:\\Users\\theor\\Desktop\\chess_game\\chess_game_cpp\\CMakeFiles\\3.27.0\\CompilerIdC\\CompilerIdC.vcxproj" (default targets) -- FAILED.
      
      Build FAILED.
      
      "C:\\Users\\theor\\Desktop\\chess_game\\chess_game_cpp\\CMakeFiles\\3.27.0\\CompilerIdC\\CompilerIdC.vcxproj" (default target) (1) ->
      (PrepareForBuild target) -> 
        C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\MSBuild\\Microsoft\\VC\\v160\\Microsoft.CppBuild.targets(434,5): warning MSB8003: The WindowsSDKDir property is not defined. Some build tools may not be found. [C:\\Users\\theor\\Desktop\\chess_game\\chess_game_cpp\\CMakeFiles\\3.27.0\\CompilerIdC\\CompilerIdC.vcxproj]
      
      
      "C:\\Users\\theor\\Desktop\\chess_game\\chess_game_cpp\\CMakeFiles\\3.27.0\\CompilerIdC\\CompilerIdC.vcxproj" (default target) (1) ->
      (Link target) -> 
        LINK : fatal error LNK1181: cannot open input file 'kernel32.lib' [C:\\Users\\theor\\Desktop\\chess_game\\chess_game_cpp\\CMakeFiles\\3.27.0\\CompilerIdC\\CompilerIdC.vcxproj]
      
          1 Warning(s)
          1 Error(s)
      
      Time Elapsed 00:00:01.33
      
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" failed.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      1
      Microsoft (R) Build Engine version 16.2.37902+b5aaefc9f for .NET Framework
      Copyright (C) Microsoft Corporation. All rights reserved.
      
      Build started 7/21/2023 8:30:57 PM.
      Project "C:\\Users\\theor\\Desktop\\chess_game\\chess_game_cpp\\CMakeFiles\\3.27.0\\CompilerIdCXX\\CompilerIdCXX.vcxproj" on node 1 (default targets).
      PrepareForBuild:
        Creating directory "Debug\\".
      C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\MSBuild\\Microsoft\\VC\\v160\\Microsoft.CppBuild.targets(434,5): warning MSB8003: The WindowsSDKDir property is not defined. Some build tools may not be found. [C:\\Users\\theor\\Desktop\\chess_game\\chess_game_cpp\\CMakeFiles\\3.27.0\\CompilerIdCXX\\CompilerIdCXX.vcxproj]
        Creating directory "Debug\\CompilerIdCXX.tlog\\".
      InitializeBuildStatus:
        Creating "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild" because "AlwaysCreate" was specified.
      ClCompile:
        C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.22.27905\\bin\\HostX64\\x64\\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc142.pdb" /Gd /TP /FC /errorReport:queue CMakeCXXCompilerId.cpp
        CMakeCXXCompilerId.cpp
      Link:
        C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.22.27905\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdCXX.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdCXX.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdCXX.lib" /MACHINE:X64 Debug\\CMakeCXXCompilerId.obj
      LINK : fatal error LNK1181: cannot open input file 'kernel32.lib' [C:\\Users\\theor\\Desktop\\chess_game\\chess_game_cpp\\CMakeFiles\\3.27.0\\CompilerIdCXX\\CompilerIdCXX.vcxproj]
      Done Building Project "C:\\Users\\theor\\Desktop\\chess_game\\chess_game_cpp\\CMakeFiles\\3.27.0\\CompilerIdCXX\\CompilerIdCXX.vcxproj" (default targets) -- FAILED.
      
      Build FAILED.
      
      "C:\\Users\\theor\\Desktop\\chess_game\\chess_game_cpp\\CMakeFiles\\3.27.0\\CompilerIdCXX\\CompilerIdCXX.vcxproj" (default target) (1) ->
      (PrepareForBuild target) -> 
        C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\MSBuild\\Microsoft\\VC\\v160\\Microsoft.CppBuild.targets(434,5): warning MSB8003: The WindowsSDKDir property is not defined. Some build tools may not be found. [C:\\Users\\theor\\Desktop\\chess_game\\chess_game_cpp\\CMakeFiles\\3.27.0\\CompilerIdCXX\\CompilerIdCXX.vcxproj]
      
      
      "C:\\Users\\theor\\Desktop\\chess_game\\chess_game_cpp\\CMakeFiles\\3.27.0\\CompilerIdCXX\\CompilerIdCXX.vcxproj" (default target) (1) ->
      (Link target) -> 
        LINK : fatal error LNK1181: cannot open input file 'kernel32.lib' [C:\\Users\\theor\\Desktop\\chess_game\\chess_game_cpp\\CMakeFiles\\3.27.0\\CompilerIdCXX\\CompilerIdCXX.vcxproj]
      
          1 Warning(s)
          1 Error(s)
      
      Time Elapsed 00:00:01.34
      
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" failed.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      1
      Microsoft (R) Build Engine version 16.2.37902+b5aaefc9f for .NET Framework
      Copyright (C) Microsoft Corporation. All rights reserved.
      
      Build started 7/21/2023 8:30:59 PM.
      Project "C:\\Users\\theor\\Desktop\\chess_game\\chess_game_cpp\\CMakeFiles\\3.27.0\\CompilerIdCXX\\CompilerIdCXX.vcxproj" on node 1 (default targets).
      PrepareForBuild:
        Creating directory "Debug\\".
      C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\MSBuild\\Microsoft\\VC\\v160\\Microsoft.CppBuild.targets(434,5): warning MSB8003: The WindowsSDKDir property is not defined. Some build tools may not be found. [C:\\Users\\theor\\Desktop\\chess_game\\chess_game_cpp\\CMakeFiles\\3.27.0\\CompilerIdCXX\\CompilerIdCXX.vcxproj]
        Creating directory "Debug\\CompilerIdCXX.tlog\\".
      InitializeBuildStatus:
        Creating "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild" because "AlwaysCreate" was specified.
      ClCompile:
        C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.22.27905\\bin\\HostX64\\x64\\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc142.pdb" /Gd /TP /FC /errorReport:queue CMakeCXXCompilerId.cpp
        CMakeCXXCompilerId.cpp
      Link:
        C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.22.27905\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdCXX.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdCXX.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdCXX.lib" /MACHINE:X64 Debug\\CMakeCXXCompilerId.obj
      LINK : fatal error LNK1181: cannot open input file 'kernel32.lib' [C:\\Users\\theor\\Desktop\\chess_game\\chess_game_cpp\\CMakeFiles\\3.27.0\\CompilerIdCXX\\CompilerIdCXX.vcxproj]
      Done Building Project "C:\\Users\\theor\\Desktop\\chess_game\\chess_game_cpp\\CMakeFiles\\3.27.0\\CompilerIdCXX\\CompilerIdCXX.vcxproj" (default targets) -- FAILED.
      
      Build FAILED.
      
      "C:\\Users\\theor\\Desktop\\chess_game\\chess_game_cpp\\CMakeFiles\\3.27.0\\CompilerIdCXX\\CompilerIdCXX.vcxproj" (default target) (1) ->
      (PrepareForBuild target) -> 
        C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\MSBuild\\Microsoft\\VC\\v160\\Microsoft.CppBuild.targets(434,5): warning MSB8003: The WindowsSDKDir property is not defined. Some build tools may not be found. [C:\\Users\\theor\\Desktop\\chess_game\\chess_game_cpp\\CMakeFiles\\3.27.0\\CompilerIdCXX\\CompilerIdCXX.vcxproj]
      
      
      "C:\\Users\\theor\\Desktop\\chess_game\\chess_game_cpp\\CMakeFiles\\3.27.0\\CompilerIdCXX\\CompilerIdCXX.vcxproj" (default target) (1) ->
      (Link target) -> 
        LINK : fatal error LNK1181: cannot open input file 'kernel32.lib' [C:\\Users\\theor\\Desktop\\chess_game\\chess_game_cpp\\CMakeFiles\\3.27.0\\CompilerIdCXX\\CompilerIdCXX.vcxproj]
      
          1 Warning(s)
          1 Error(s)
      
      Time Elapsed 00:00:01.56
      
      
...
